### ISSUE TITLE
Feature Request: Alliterative IDs

### ISSUE THREAD

**Issue by gadenbuie** [richfitz/ids#5]
This package is awesome and the IDs are always fantastic. But I think they're even better when they're alliterative. I think `hessian_halibut` nicely proves my point in this small example below.

```r
library(tidyverse)
tibble(
  id = ids::adjective_animal(1e4, max_len = c(7, 8)),
  first_word = str_sub(id, 1, 1),
  second_word = str_sub(str_extract(id, "_\\w"), 2, 2)
) %>% 
  filter(first_word == second_word) %>% 
  sample_n(25) %>% 
  pull(id)
##  [1] "coal_civet"       "lethal_lorikeet"  "dwarven_dinosaur" "sincere_shrimp"   "ash_angora"      
##  [6] "huge_hoopoe"      "cutrate_cow"      "brassy_betafish"  "hessian_halibut"  "spotty_sable"    
## [11] "married_magpie"   "uneasy_urubu"     "pattern_pupa"     "augite_axisdeer"  "dermoid_drongo"  
## [16] "merry_marlin"     "plaid_piranha"    "chic_chital"      "skilled_spider"   "cold_cygnet"     
## [21] "covert_chafer"    "softish_seriema"  "classy_coypu"     "smiling_serpent"  "rattish_redpoll" 
```

I was half-joking when I proposed this on Twitter, but after looking at quite a few iterations of alliterative IDs I think they may actually be easier to work with -- or at least they're easier for me to remember over short time spans.

**Edit:** Just to be overly specific, the FR is for an `alliterative` argument in `adjective_animal()` with a default value of `FALSE`.

**Comment by richfitz** [comment]
Travis is not happy at the moment, but this is implemented now on the `i5_alliterate` branch

**Comment by gadenbuie** [comment]
woot! Thanks @richfitz for making it happen!
